encoding: "utf-8"
exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
title: "Gemeinschaftspraxis - Frauenärztinnen Drs. Monika Burger & Julia Gantert - Münster-Handorf"
email: gyn-handorf@web.de
description: Gemeinschaftspraxis für Gynäkologie & Psychotherapie von Frauenärztinnen Drs. Monika Burger & Julia Gantert in Münster-Handorf
url: "http://frauenaerztinnen-muenster-handorf.de"
defaults:
  -
    values:
      layout: 'default'